name: Release Process

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Java 21)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Install Gradle (if not using wrapper, otherwise skip this step)
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.2-bin.zip
          unzip gradle-7.2-bin.zip
          export GRADLE_HOME=$PWD/gradle-7.2
          export PATH=$GRADLE_HOME/bin:$PATH

      # Step 4: Build the project with Gradle
      - name: Build the project
        run: ./gradlew build  # Builds the project and generates the JAR file

      # Step 5: Upload the JAR file as a release artifact
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-project-v1.0.0-jar
          path: build/libs/*.jar  # Adjust the path if necessary

  release:
    runs-on: ubuntu-latest
    needs: build  # Ensures the release job runs only after the build job is successful

    steps:
      # Step 1: Checkout code again to get the tag context
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Create the GitHub release
      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar  # Upload the JAR file created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



