name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows the action to write to the repo

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 21 (use your Java version)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Grant execute permission for Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # Build the project with Gradle (or Maven if you're using that)
      - name: Build with Gradle
        run: ./gradlew build

      # Run tests (you can skip if you don't have any)
      - name: Run Tests
        run: ./gradlew test

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      # Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Create a GitHub release
      - name: Create GitHub Release
        run: |
          tag="${GITHUB_REF#refs/tags/}"  # Extract tag name
          gh release create "$tag" ./build/libs/*.jar --title "$tag" --notes "Release $tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


